version: 1.0.{build}
configuration: Release
image: Visual Studio 2019
platform: x86
install:
- cd C:\Tools\vcpkg
- git pull
- .\bootstrap-vcpkg.bat
- vcpkg integrate install
- cd %APPVEYOR_BUILD_FOLDER%
- vcpkg install sqlite3:x86-windows
build:
  project: OrinrinEditor.vcxproj
  parallel: true
  verbosity: minimal
before_build:
- chcp 932
artifacts:
- path: ./OrinrinEditor.vcxproj
cache: c:\tools\vcpkg\installed\
