version: 1.0.{build}
configuration: Release
environment:
  matrix:
    - PLATFORM: Win32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - PLATFORM: x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

install:
- cmd: >-
    cd C:\Tools\vcpkg

    git pull

    .\bootstrap-vcpkg.bat

    vcpkg integrate install

    cd %APPVEYOR_BUILD_FOLDER%

    vcpkg install sqlite3:x64-windows

    vcpkg install sqlite3:x86-windows
before_build:
- cmd: chcp 932
build:
  project: OrinrinEditor.vcxproj
  parallel: true
  verbosity: minimal
after_build:
- ps: .\package.ps1
artifacts:
- path: ./OrinrinEditor-x64.zip
  name: OrinrinEditor-x64
- path: ./OrinrinEditor-x86.zip
  name: OrinrinEditor-x86
