version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
platform: x64
install:
- cmd: >-
    cd C:\Tools\vcpkg

    git pull

    .\bootstrap-vcpkg.bat

    vcpkg integrate install

    cd %APPVEYOR_BUILD_FOLDER%

    vcpkg install sqlite3:x64-windows

    vcpkg install sqlite3:x86-windows
build_script:
- cmd: >-
    msbuild "%APPVEYOR_BUILD_FOLDER%\OrinrinEditor.vcxproj" /m /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /t:build /p:Configuration=Debug;Platform="x64"

    msbuild "%APPVEYOR_BUILD_FOLDER%\OrinrinEditor.vcxproj" /m /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /t:build /p:Configuration=Debug;Platform="Win32"
artifacts:
- path: ./OrinrinEditor-x64.zip
  name: OrinrinEditor-x64
- path: ./OrinrinEditor-x86.zip
  name: OrinrinEditor-x86
